---
title: "TSA Competition"
author: "Aditi Jackson and Cara Kuuskvere"
date: "2024-03-28"
output: pdf_document
---

```{r setup}
library(lubridate)
library(ggplot2)
library(forecast)
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(dplyr)
library(readr)
library(readxl)
library(zoo)

```

## Data

```{r data, echo=FALSE}

# loading data
load_RAW <- read_excel("./Data/load.xlsx",col_names=TRUE,na="NA")
humidity_RAW <- read_excel("./Data/relative_humidity.xlsx",col_names=TRUE)
temperature_RAW <- read_excel("./Data/temperature.xlsx",col_names=TRUE)

# cleaning data in pipe
load_clean <- load_RAW %>%
  mutate(date = ymd(date)) %>%  ## create date object
  mutate(daily_average = rowMeans(select(., h1:h24))) %>% # transforming hourly data into daily data
  select(-h1:-h24) %>% # dropping hourly columns
  select(-meter_id)  ## drop meter ID


load_clean$daily_average <- na.approx(load_clean$daily_average)

## check for missing dates by creating dummy data frame for dates
Days <- as.data.frame(seq.Date(from=as.Date("2005/01/01"),to=as.Date("2011/06/30"), by ="day"))
colnames(Days) <- "date"

#merge with the data with missing rows
date_check <-left_join(Days, load_clean, by="date")

# checking N/As
check_na <- is.na(date_check)
colSums(check_na) 



```

```{r Create ts object, include=FALSE}
ts_load <- ts(load_clean[,2],  start=c(year(load_clean$date[1]),month(load_clean$date[1]),day(load_clean$date[1])),
                           frequency=365)
head(ts_load,15)
tail(ts_load,15)  
tsclean(ts_load)
#na.approx(ts_load)
#which(is.na(ts_load))
```

```{r Initial plots}

TS_Plot <- 
  ggplot(load_clean, aes(x=date, y=daily_average)) +
      geom_line()
plot(TS_Plot)

#ACF and PACF plots
par(mfrow=c(1,2))
ACF_Plot <- Acf(load_clean$daily_average, lag = 40, plot = TRUE)
PACF_Plot <- Pacf(load_clean$daily_average, lag = 40)
par(mfrow=c(1,1))

```
The initial plots show an weak exponential decay on the ACF and a strong correlation at lag 1 on the PACF. The TS plot shows at least two strong seasonal components; with seasonality within the years as well as seasonality within the months due to regular sinusoidal oscillations. 

```{r}
#Using R decompose function
decompose_load <- decompose(ts_load[,"daily_average"],"additive")
plot(decompose_load)

#The ACF plot show a slow decay which is a sign of non-stationarity.

#Creating non-seasonal residential price time series because some models can't handle seasonality
deseasonal_load <- seasadj(decompose_load)  

```

